name: Build Docker Compose
on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build services and then run Docker Compose
      run: docker compose up --build
