name: Worker Image CI Test

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file highload-worker/worker_test.Dockerfile -t highload-worker-test
        docker run highload-worker-test
